[workspace]
authors = ["Boubacar Sow <boubasow.pro@gmail.com>"]
channels = ["conda-forge"]
name = "cued_speech"
platforms = ["linux-64"]
version = "0.1.8"



[tasks]

[dependencies]
python = "3.11.*"
moviepy = "1.0.3.*"
praatio = "6.0.0.*"
montreal-forced-aligner = ">=3.3.4,<4"
joblib = "1.3.2.*"

[pypi-dependencies]
kenlm = ">=0.3.0, <0.4"
praat-textgrids = ">=1.4.0, <2"
click = "*"
numpy = "*"
pandas = ">=2.3.1, <3"
mediapipe = ">=0.10.14, <0.11"
opencv-python = ">=4.12.0.88, <5"
torch = ">=2.2.2, <2.3"
torchvision = ">=0.17.2, <0.18"
absl-py = ">=2.3.1, <3"
unicodedata2 = "*"
whisper = ">=1.1.10, <2"
black = ">=25.1.0, <26"
isort = ">=6.0.1, <7"
pytest = ">=8.4.1, <9"
pytest-cov = ">=6.2.1, <7"
mypy = ">=1.17.1, <2"
flake8 = ">=7.3.0, <8"
torchaudio = ">=2.2.2, <2.3"
flashlight-text = ">=0.0.7, <0.0.8"
openai-whisper = ">=20250625, <20250626"
praatio = "*"
