[workspace]
authors = ["Boubacar Sow <boubasow.pro@gmail.com>"]
channels = ["conda-forge"]
name = "cued_speech"
platforms = ["linux-64"]
version = "0.2.55"

[tasks]

[dependencies]
moviepy = "==1.0.3"
python = "3.11.*"
twine = ">=6.1.0,<7"
montreal-forced-aligner = "3.3.4.*"
praatio = ">=6.2.0,<7"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
kenlm = ">=0.3.0, <0.4"
click = "*"
numpy = "*"
pandas = ">=2.3.1, <3"
mediapipe = ">=0.10.14, <0.11"
opencv-python = ">=4.12.0.88, <5"
torch = "==2.2.2"
torchvision = ">=0.17.2, <0.18"
unicodedata2 = "*"
openai-whisper = ">=20250625, <20250626"
isort = ">=6.0.1, <7"
pytest = ">=8.4.1, <9"
mypy = ">=1.17.1, <2"
flake8 = ">=7.3.0, <8"
torchaudio = "==2.2.2"
flashlight-text = ">=0.0.7, <0.0.8"
black = ">=25.1.0, <26"
praat-textgrids = ">=1.4.0, <2"
build = ">=1.3.0, <2"
joblib = "*"
