#ifndef TENSORFLOW_LITE_CORE_ASYNC_INTEROP_C_TYPES_H_
#define TENSORFLOW_LITE_CORE_ASYNC_INTEROP_C_TYPES_H_

#include "tensorflow/lite/core/async/c/types.h"

#endif  // TENSORFLOW_LITE_CORE_ASYNC_INTEROP_C_TYPES_H_

